### ISSUE TITLE
Compile instructions

### ISSUE THREAD

**Issue by willythewonka** [dkmfbk/rdfpro#9]
How can I comiple the rdfpro command line tools? I can't find any instructions in this repository.

**Comment by petrux** [comment]
I did the following:  
  
:~$ git clone git@github.com:dkmfbk/rdfpro.git
:~$ cd rdfpro
:~$ mvn package

so I think that there is not particular trick for building `rdfpro` -- once you have `Maven` installed, of course.

**Comment by willythewonka** [comment]
Alright, thanks a lot. Leaving this issue open for now, because I think it would be useful to add these instructions in a README for people like me who are not familiar with Java build tools.

**Comment by fracor** [comment]
Fine with leaving the issue open and thanks for pointing this out! I'll add a page on github or the website as part of the next release of RDFpro (we are migrating from SESAME to RDF4J) and then close the issue.

I'm adding here some details to the instructions provided by @petrux (thanks!):
```
  $ git clone git@github.com:dkmfbk/rdfpro.git  (1)
  $ cd rdfpro                                   (2)
  $ git checkout BRANCH_NAME                    (3)
  $ mvn package -DskipTests -Prelease           (4)
```
Step (3) is optional and is needed if one wants to use the latest version of the code (generally it is develop, although we are currently working on branch rdf4j due to the aforementioned migration).

The flags in step (4) disable unit testing to speed up building, and activate a Maven profile called "release" that enables the generation of the same tar.gz archive including everything that we distribute as RDFpro binaries on the website. This tar.gz is located under:
```
  rdfpro-dist/target/rdfpro-dist-VERSION-bin.tar.gz
```
You may copy it wherever you want, extract it and run rdfpro via the included 'rdfpro' script.

**Comment by petrux** [comment]
As a side note (and minor issue), step (1) assumes developer is using the SSH connection and not HTTPS. If @fracor is fine with that, he can assign this issue to me and I will fix the `README.md`.

**Comment by willythewonka** [comment]
> I'll add a page on github or the website as part of the next release of RDFpro

Your website already has a lot of good documentation, so I guess it would make sense to add this information both in a README (such that it's downloaded with the repo) and on your website as well. Using GitHub for this (either GitHub pages or Wikis) doesn't look like a good option to me.

Thanks a lot for your great reply.
